#ifndef OPENUSD_BASE_H
#define OPENUSD_BASE_H



// tf
#include <Base/tf/anyUniquePtr.h>
#include <Base/tf/anyWeakPtr.h>
#include <Base/tf/api.h>
#include <Base/tf/atomicOfstreamWrapper.h>
#include <Base/tf/atomicRenameUtil.h>
#include <Base/tf/bigRWMutex.h>
#include <Base/tf/bitUtils.h>
#include <Base/tf/callContext.h>
#include <Base/tf/cxxCast.h>
#include <Base/tf/debug.h>
#include <Base/tf/debugCodes.h>
#include <Base/tf/debugNotice.h>
#include <Base/tf/declarePtrs.h>
#include <Base/tf/denseHashMap.h>
#include <Base/tf/denseHashSet.h>
#include <Base/tf/diagnostic.h>
#include <Base/tf/diagnosticBase.h>
#include <Base/tf/diagnosticHelper.h>
#include <Base/tf/diagnosticLite.h>
#include <Base/tf/diagnosticMgr.h>
#include <Base/tf/dl.h>
#include <Base/tf/enum.h>
#include <Base/tf/envSetting.h>
#include <Base/tf/error.h>
#include <Base/tf/errorMark.h>
#include <Base/tf/errorTransport.h>
#include <Base/tf/exception.h>
#include <Base/tf/expiryNotifier.h>
#include <Base/tf/fastCompression.h>
#include <Base/tf/fileUtils.h>
#include <Base/tf/functionRef.h>
#include <Base/tf/functionTraits.h>
#include <Base/tf/getenv.h>
#include <Base/tf/hash.h>
#include <Base/tf/hashmap.h>
#include <Base/tf/hashset.h>
#include <Base/tf/instantiateSingleton.h>
#include <Base/tf/instantiateStacked.h>
#include <Base/tf/instantiateType.h>
#include <Base/tf/iterator.h>
#include <Base/tf/makePyConstructor.h>
#include <Base/tf/mallocTag.h>
#include <Base/tf/meta.h>
#include <Base/tf/notice.h>
#include <Base/tf/noticeRegistry.h>
#include <Base/tf/nullPtr.h>
#include <Base/tf/ostreamMethods.h>
#include <Base/tf/pathUtils.h>
#include <Base/tf/patternMatcher.h>
#include <Base/tf/pch.h>
#include <Base/tf/pointerAndBits.h>
#include <Base/tf/preprocessorUtils.h>
#include <Base/tf/preprocessorUtilsLite.h>
#include <Base/tf/py3Compat.h>
#include <Base/tf/pyAnnotatedBoolResult.h>
#include <Base/tf/pyArg.h>
#include <Base/tf/pyCall.h>
#include <Base/tf/pyCallContext.h>
#include <Base/tf/pyClassMethod.h>
#include <Base/tf/pyContainerConversions.h>
#include <Base/tf/pyEnum.h>
#include <Base/tf/pyError.h>
#include <Base/tf/pyErrorInternal.h>
#include <Base/tf/pyExceptionState.h>
#include <Base/tf/pyFunction.h>
#include <Base/tf/pyIdentity.h>
#include <Base/tf/pyInterpreter.h>
#include <Base/tf/pyInvoke.h>
#include <Base/tf/pyLock.h>
#include <Base/tf/pyModule.h>
#include <Base/tf/pyModuleNotice.h>
#include <Base/tf/pyNoticeWrapper.h>
#include <Base/tf/pyObjectFinder.h>
#include <Base/tf/pyObjWrapper.h>
#include <Base/tf/pyOptional.h>
#include <Base/tf/pyOverride.h>
#include <Base/tf/pyPolymorphic.h>
#include <Base/tf/pyPtrHelpers.h>
#include <Base/tf/pyResultConversions.h>
#include <Base/tf/pySafePython.h>
#include <Base/tf/pySignatureExt.h>
#include <Base/tf/pySingleton.h>
#include <Base/tf/pyStaticTokens.h>
#include <Base/tf/pyTracing.h>
#include <Base/tf/pyUtils.h>
#include <Base/tf/pyWeakObject.h>
#include <Base/tf/pyWrapContext.h>
#include <Base/tf/refBase.h>
#include <Base/tf/refCount.h>
#include <Base/tf/refPtr.h>
#include <Base/tf/refPtrTracker.h>
#include <Base/tf/registryManager.h>
#include <Base/tf/regTest.h>
#include <Base/tf/safeOutputFile.h>
#include <Base/tf/safeTypeCompare.h>
#include <Base/tf/scoped.h>
#include <Base/tf/scopeDescription.h>
#include <Base/tf/scopeDescriptionPrivate.h>
#include <Base/tf/scriptModuleLoader.h>
#include <Base/tf/setenv.h>
#include <Base/tf/singleton.h>
#include <Base/tf/smallVector.h>
#include <Base/tf/span.h>
#include <Base/tf/spinRWMutex.h>
#include <Base/tf/stacked.h>
#include <Base/tf/stackTrace.h>
#include <Base/tf/staticData.h>
#include <Base/tf/staticTokens.h>
#include <Base/tf/status.h>
#include <Base/tf/stl.h>
#include <Base/tf/stopwatch.h>
#include <Base/tf/stringUtils.h>
#include <Base/tf/templateString.h>
#include <Base/tf/Tf.h>
#include <Base/tf/token.h>
#include <Base/tf/type_Impl.h>
#include <Base/tf/type.h>
#include <Base/tf/typeFunctions.h>
#include <Base/tf/typeInfoMap.h>
#include <Base/tf/typeNotice.h>
#include <Base/tf/warning.h>
#include <Base/tf/weakBase.h>
#include <Base/tf/weakPtr.h>
#include <Base/tf/weakPtrFacade.h>
#include <Base/tf/wrapTypeHelpers.h>
#include <Base/tf/pxrLZ4/lz4.h>
#include <Base/tf/pxrDoubleConversion/bignum-dtoa.h>
#include <Base/tf/pxrDoubleConversion/bignum.h>
#include <Base/tf/pxrDoubleConversion/cached-powers.h>
#include <Base/tf/pxrDoubleConversion/diy-fp.h>
#include <Base/tf/pxrDoubleConversion/double-conversion.h>
#include <Base/tf/pxrDoubleConversion/fast-dtoa.h>
#include <Base/tf/pxrDoubleConversion/fixed-dtoa.h>
#include <Base/tf/pxrDoubleConversion/ieee.h>
#include <Base/tf/pxrDoubleConversion/strtod.h>
#include <Base/tf/pxrDoubleConversion/utils.h>
#include <Base/tf/pxrPEGTL/pegtl.h>
#include <Base/tf/pxrTslRobinMap/robin_growth_policy.h>
#include <Base/tf/pxrTslRobinMap/robin_hash.h>
#include <Base/tf/pxrTslRobinMap/robin_map.h>
#include <Base/tf/pxrTslRobinMap/robin_set.h>
#include <Base/tf/pxrCLI11/CLI11.h>

// vt
#include <Base/vt/api.h>
#include <Base/vt/array.h>
#include <Base/vt/arrayPyBuffer.h>
#include <Base/vt/dictionary.h>
#include <Base/vt/functions.h>
#include <Base/vt/hash.h>
#include <Base/vt/pch.h>
#include <Base/vt/pyOperators.h>
#include <Base/vt/streamOut.h>
#include <Base/vt/traits.h>
#include <Base/vt/typeHeaders.h>
#include <Base/vt/types.h>
#include <Base/vt/value.h>
#include <Base/vt/valueFromPython.h>
#include <Base/vt/visitValue.h>
#include <Base/vt/wrapArray.h>

// gf
#include <Base/gf/api.h>
#include <Base/gf/bbox3d.h>
#include <Base/gf/camera.h>
#include <Base/gf/declare.h>
#include <Base/gf/dualQuatd.h>
#include <Base/gf/dualQuatf.h>
#include <Base/gf/dualQuath.h>
#include <Base/gf/frustum.h>
#include <Base/gf/gamma.h>
#include <Base/gf/half.h>
#include <Base/gf/homogeneous.h>
#include <Base/gf/ilmbase_eLut.h>
#include <Base/gf/ilmbase_half.h>
#include <Base/gf/ilmbase_halfLimits.h>
#include <Base/gf/ilmbase_toFloat.h>
#include <Base/gf/interval.h>
#include <Base/gf/limits.h>
#include <Base/gf/line.h>
#include <Base/gf/line2d.h>
#include <Base/gf/lineSeg.h>
#include <Base/gf/lineSeg2d.h>
#include <Base/gf/math.h>
#include <Base/gf/matrix2d.h>
#include <Base/gf/matrix2f.h>
#include <Base/gf/matrix3d.h>
#include <Base/gf/matrix3f.h>
#include <Base/gf/matrix4d.h>
#include <Base/gf/matrix4f.h>
#include <Base/gf/matrixData.h>
#include <Base/gf/multiInterval.h>
#include <Base/gf/ostreamHelpers.h>
#include <Base/gf/pch.h>
#include <Base/gf/plane.h>
#include <Base/gf/pyBufferUtils.h>
#include <Base/gf/quatd.h>
#include <Base/gf/quaternion.h>
#include <Base/gf/quatf.h>
#include <Base/gf/quath.h>
#include <Base/gf/range1d.h>
#include <Base/gf/range1f.h>
#include <Base/gf/range2d.h>
#include <Base/gf/range2f.h>
#include <Base/gf/range3d.h>
#include <Base/gf/range3f.h>
#include <Base/gf/ray.h>
#include <Base/gf/rect2i.h>
#include <Base/gf/rotation.h>
#include <Base/gf/size2.h>
#include <Base/gf/size3.h>
#include <Base/gf/traits.h>
#include <Base/gf/transform.h>
#include <Base/gf/vec2d.h>
#include <Base/gf/vec2f.h>
#include <Base/gf/vec2h.h>
#include <Base/gf/vec2i.h>
#include <Base/gf/vec3d.h>
#include <Base/gf/vec3f.h>
#include <Base/gf/vec3h.h>
#include <Base/gf/vec3i.h>
#include <Base/gf/vec4d.h>
#include <Base/gf/vec4f.h>
#include <Base/gf/vec4h.h>
#include <Base/gf/vec4i.h>

// trace
#include <Base/trace/aggregateNode.h>
#include <Base/trace/aggregateTree.h>
#include <Base/trace/aggregateTreeBuilder.h>
#include <Base/trace/api.h>
#include <Base/trace/category.h>
#include <Base/trace/collection.h>
#include <Base/trace/collectionNotice.h>
#include <Base/trace/collector.h>
#include <Base/trace/concurrentList.h>
#include <Base/trace/counterAccumulator.h>
#include <Base/trace/dataBuffer.h>
#include <Base/trace/dynamicKey.h>
#include <Base/trace/event.h>
#include <Base/trace/eventContainer.h>
#include <Base/trace/eventData.h>
#include <Base/trace/eventList.h>
#include <Base/trace/eventNode.h>
#include <Base/trace/eventTree.h>
#include <Base/trace/eventTreeBuilder.h>
#include <Base/trace/jsonSerialization.h>
#include <Base/trace/key.h>
#include <Base/trace/pch.h>
#include <Base/trace/reporter.h>
#include <Base/trace/reporterBase.h>
#include <Base/trace/reporterDataSourceBase.h>
#include <Base/trace/reporterDataSourceCollection.h>
#include <Base/trace/reporterDataSourceCollector.h>
#include <Base/trace/serialization.h>
#include <Base/trace/staticKeyData.h>
#include <Base/trace/stringHash.h>
#include <Base/trace/threads.h>
#include <Base/trace/trace.h>

// js
#include <Base/js/api.h>
#include <Base/js/converter.h>
#include <Base/js/json.h>
#include <Base/js/pch.h>
#include <Base/js/types.h>
#include <Base/js/utils.h>
#include <Base/js/value.h>
#if defined(_WIN32)
#include <Base/js/rapidjson/msinttypes/inttypes.h>
#include <Base/js/rapidjson/msinttypes/stdint.h>
#endif // defined(_WIN32)
#include <Base/js/rapidjson/internal/biginteger.h>
#include <Base/js/rapidjson/internal/clzll.h>
#include <Base/js/rapidjson/internal/diyfp.h>
#include <Base/js/rapidjson/internal/dtoa.h>
#include <Base/js/rapidjson/internal/ieee754.h>
#include <Base/js/rapidjson/internal/itoa.h>
#include <Base/js/rapidjson/internal/meta.h>
#include <Base/js/rapidjson/internal/pow10.h>
#include <Base/js/rapidjson/internal/regex.h>
#include <Base/js/rapidjson/internal/stack.h>
#include <Base/js/rapidjson/internal/strfunc.h>
#include <Base/js/rapidjson/internal/strtod.h>
#include <Base/js/rapidjson/internal/swap.h>
#include <Base/js/rapidjson/error/en.h>
#include <Base/js/rapidjson/error/error.h>
#include <Base/js/rapidjson/allocators.h>
#include <Base/js/rapidjson/cursorstreamwrapper.h>
#include <Base/js/rapidjson/document.h>
#include <Base/js/rapidjson/encodedstream.h>
#include <Base/js/rapidjson/encodings.h>
#include <Base/js/rapidjson/filereadstream.h>
#include <Base/js/rapidjson/filewritestream.h>
#include <Base/js/rapidjson/fwd.h>
#include <Base/js/rapidjson/istreamwrapper.h>
#include <Base/js/rapidjson/memorybuffer.h>
#include <Base/js/rapidjson/memorystream.h>
#include <Base/js/rapidjson/ostreamwrapper.h>
#include <Base/js/rapidjson/pointer.h>
#include <Base/js/rapidjson/prettywriter.h>
#include <Base/js/rapidjson/rapidjson.h>
#include <Base/js/rapidjson/reader.h>
#include <Base/js/rapidjson/schema.h>
#include <Base/js/rapidjson/stream.h>
#include <Base/js/rapidjson/stringbuffer.h>
#include <Base/js/rapidjson/uri.h>
#include <Base/js/rapidjson/writer.h>

// work
#include <Base/work/api.h>
#include <Base/work/detachedTask.h>
#include <Base/work/dispatcher.h>
#include <Base/work/loops.h>
#include <Base/work/pch.h>
#include <Base/work/reduce.h>
#include <Base/work/singularTask.h>
#include <Base/work/threadLimits.h>
#include <Base/work/utils.h>
#include <Base/work/withScopedParallelism.h>

// plug
#include <Base/plug/api.h>
#include <Base/plug/debugCodes.h>
#include <Base/plug/info.h>
#include <Base/plug/interfaceFactory.h>
#include <Base/plug/notice.h>
#include <Base/plug/pch.h>
#include <Base/plug/plugin.h>
#include <Base/plug/registry.h>
#include <Base/plug/staticInterface.h>
#include <Base/plug/testPlugBase.h>
#include <Base/plug/thisPlugin.h>

#endif /* OPENUSD_BASE_H */
