#ifndef OPENUSD_BASE_H
#define OPENUSD_BASE_H

// vt
#include <Base/vt/api.h>
#include <Base/vt/array.h>
#include <Base/vt/arrayPyBuffer.h>
#include <Base/vt/dictionary.h>
#include <Base/vt/functions.h>
#include <Base/vt/hash.h>
#include <Base/vt/pch.h>
#include <Base/vt/pyOperators.h>
#include <Base/vt/streamOut.h>
#include <Base/vt/traits.h>
#include <Base/vt/typeHeaders.h>
#include <Base/vt/types.h>
#include <Base/vt/value.h>
#include <Base/vt/valueFromPython.h>
#include <Base/vt/visitValue.h>
#include <Base/vt/wrapArray.h>

// trace
#include <Base/trace/aggregateNode.h>
#include <Base/trace/aggregateTree.h>
#include <Base/trace/aggregateTreeBuilder.h>
#include <Base/trace/api.h>
#include <Base/trace/category.h>
#include <Base/trace/collection.h>
#include <Base/trace/collectionNotice.h>
#include <Base/trace/collector.h>
#include <Base/trace/concurrentList.h>
#include <Base/trace/counterAccumulator.h>
#include <Base/trace/dataBuffer.h>
#include <Base/trace/dynamicKey.h>
#include <Base/trace/event.h>
#include <Base/trace/eventContainer.h>
#include <Base/trace/eventData.h>
#include <Base/trace/eventList.h>
#include <Base/trace/eventNode.h>
#include <Base/trace/eventTree.h>
#include <Base/trace/eventTreeBuilder.h>
#include <Base/trace/jsonSerialization.h>
#include <Base/trace/key.h>
#include <Base/trace/pch.h>
#include <Base/trace/reporter.h>
#include <Base/trace/reporterBase.h>
#include <Base/trace/reporterDataSourceBase.h>
#include <Base/trace/reporterDataSourceCollection.h>
#include <Base/trace/reporterDataSourceCollector.h>
#include <Base/trace/serialization.h>
#include <Base/trace/staticKeyData.h>
#include <Base/trace/stringHash.h>
#include <Base/trace/threads.h>
#include <Base/trace/trace.h>

// js
#include <Base/js/api.h>
#include <Base/js/converter.h>
#include <Base/js/json.h>
#include <Base/js/pch.h>
#include <Base/js/types.h>
#include <Base/js/utils.h>
#include <Base/js/value.h>
#if defined(_WIN32)
#include <Base/js/rapidjson/msinttypes/inttypes.h>
#include <Base/js/rapidjson/msinttypes/stdint.h>
#endif // defined(_WIN32)
#include <Base/js/rapidjson/internal/biginteger.h>
#include <Base/js/rapidjson/internal/clzll.h>
#include <Base/js/rapidjson/internal/diyfp.h>
#include <Base/js/rapidjson/internal/dtoa.h>
#include <Base/js/rapidjson/internal/ieee754.h>
#include <Base/js/rapidjson/internal/itoa.h>
#include <Base/js/rapidjson/internal/meta.h>
#include <Base/js/rapidjson/internal/pow10.h>
#include <Base/js/rapidjson/internal/regex.h>
#include <Base/js/rapidjson/internal/stack.h>
#include <Base/js/rapidjson/internal/strfunc.h>
#include <Base/js/rapidjson/internal/strtod.h>
#include <Base/js/rapidjson/internal/swap.h>
#include <Base/js/rapidjson/error/en.h>
#include <Base/js/rapidjson/error/error.h>
#include <Base/js/rapidjson/allocators.h>
#include <Base/js/rapidjson/cursorstreamwrapper.h>
#include <Base/js/rapidjson/document.h>
#include <Base/js/rapidjson/encodedstream.h>
#include <Base/js/rapidjson/encodings.h>
#include <Base/js/rapidjson/filereadstream.h>
#include <Base/js/rapidjson/filewritestream.h>
#include <Base/js/rapidjson/fwd.h>
#include <Base/js/rapidjson/istreamwrapper.h>
#include <Base/js/rapidjson/memorybuffer.h>
#include <Base/js/rapidjson/memorystream.h>
#include <Base/js/rapidjson/ostreamwrapper.h>
#include <Base/js/rapidjson/pointer.h>
#include <Base/js/rapidjson/prettywriter.h>
#include <Base/js/rapidjson/rapidjson.h>
#include <Base/js/rapidjson/reader.h>
#include <Base/js/rapidjson/schema.h>
#include <Base/js/rapidjson/stream.h>
#include <Base/js/rapidjson/stringbuffer.h>
#include <Base/js/rapidjson/uri.h>
#include <Base/js/rapidjson/writer.h>

// work
#include <Base/work/api.h>
#include <Base/work/detachedTask.h>
#include <Base/work/dispatcher.h>
#include <Base/work/loops.h>
#include <Base/work/pch.h>
#include <Base/work/reduce.h>
#include <Base/work/singularTask.h>
#include <Base/work/threadLimits.h>
#include <Base/work/utils.h>
#include <Base/work/withScopedParallelism.h>

// plug
#include <Base/plug/api.h>
#include <Base/plug/debugCodes.h>
#include <Base/plug/info.h>
#include <Base/plug/interfaceFactory.h>
#include <Base/plug/notice.h>
#include <Base/plug/pch.h>
#include <Base/plug/plugin.h>
#include <Base/plug/registry.h>
#include <Base/plug/staticInterface.h>
#include <Base/plug/testPlugBase.h>
#include <Base/plug/thisPlugin.h>

#endif /* OPENUSD_BASE_H */
