#ifndef __PXR_USD_SDF_H__
#define __PXR_USD_SDF_H__

// sdf
#include <Sdf/api.h>

//#include <Sdf/abstractData.h>
//#include <Sdf/accessorHelpers.h>
//#include <Sdf/allowed.h>
#include <Sdf/assetPath.h>
#include <Sdf/assetPathResolver.h>
#include <Sdf/attributeSpec.h>
//#include <Sdf/changeBlock.h>
//#include <Sdf/changeList.h>
//#include <Sdf/changeManager.h>
//#include <Sdf/children.h>
//#include <Sdf/childrenPolicies.h>
//#include <Sdf/childrenProxy.h>
//#include <Sdf/childrenUtils.h>
//#include <Sdf/childrenView.h>
//#include <Sdf/cleanupEnabler.h>
//#include <Sdf/cleanupTracker.h>
//#include <Sdf/connectionListEditor.h>
//#include <Sdf/copyUtils.h>
//#include <Sdf/data.h>
//#include <Sdf/debugCodes.h>
#include <Sdf/declareHandles.h>
#include <Sdf/declareSpec.h>
#include <Sdf/fileFormat.h>
//#include <Sdf/fileFormatRegistry.h>
//#include <Sdf/fileIO_Common.h>
//#include <Sdf/fileIO.h>
//#include <Sdf/identity.h>
//#include <Sdf/instantiatePool.h>
//#include <Sdf/invoke.hpp>
#include <Sdf/layer.h>
//#include <Sdf/layerHints.h>
#include <Sdf/layerOffset.h>
//#include <Sdf/layerRegistry.h>
//#include <Sdf/layerStateDelegate.h>
#include <Sdf/layerTree.h>
//#include <Sdf/layerUtils.h>
//#include <Sdf/listEditor.h>
//#include <Sdf/listEditorProxy.h>
//#include <Sdf/listOp.h>
//#include <Sdf/listOpListEditor.h>
//#include <Sdf/listProxy.h>
//#include <Sdf/mapEditor.h>
//#include <Sdf/mapEditProxy.h>
//#include <Sdf/namespaceEdit.h>
#include <Sdf/notice.h>
//#include <Sdf/opaqueValue.h>
//#include <Sdf/parserHelpers.h>
//#include <Sdf/parserValueContext.h>
#include <Sdf/path.h>
//#include <Sdf/pathExpression.h>
//#include <Sdf/pathExpressionEval.h>
//#include <Sdf/pathNode.h>
#include <Sdf/pathTable.h>
#include <Sdf/payload.h>
//#include <Sdf/pool.h>
//#include <Sdf/predicateExpression.h>
// #include <Sdf/predicateExpressionParser.h>
// #include <Sdf/predicateLibrary.h>
//#include <Sdf/predicateProgram.h>
#include <Sdf/primSpec.h>
//#include <Sdf/propertySpec.h>
//#include <Sdf/proxyPolicies.h>
//#include <Sdf/proxyTypes.h>
//#include <Sdf/pseudoRootSpec.h>
//#include <Sdf/pyChildrenProxy.h>
//#include <Sdf/pyChildrenView.h>
//#include <Sdf/pyListEditorProxy.h>
//#include <Sdf/pyListOp.h>
//#include <Sdf/pyListProxy.h>
//#include <Sdf/pyMapEditProxy.h>
//#include <Sdf/pySpec.h>
//#include <Sdf/pyUtils.h>
#include <Sdf/reference.h>
#include <Sdf/relationshipSpec.h>
//#include <Sdf/schema.h>
//#include <Sdf/schemaTypeRegistration.h>
#include <Sdf/site.h>
//#include <Sdf/siteUtils.h>
//#include <Sdf/spec.h>
#include <Sdf/specType.h>
//#include <Sdf/subLayerListEditor.h>
#include <Sdf/textFileFormat.h>
//
//#include <Sdf/textFileFormat.tab.h>
//
//#include <Sdf/textParserContext.h>
//#include <Sdf/timeCode.h>
//#include <Sdf/tokens.h>
#include <Sdf/types.h>
//#include <Sdf/valueTypeName.h>
//#include <Sdf/valueTypePrivate.h>
//#include <Sdf/valueTypeRegistry.h>
//#include <Sdf/variableExpression.h>
//#include <Sdf/variableExpressionImpl.h>
//#include <Sdf/variableExpressionParser.h>
#include <Sdf/variantSetSpec.h>
#include <Sdf/variantSpec.h>
//#include <Sdf/vectorListEditor.h>

#endif // __PXR_USD_SDF_H__
