//===----------------------------------------------------------------------===//
// This source file is taken from github.com/apple/SwiftUsd
//
// Copyright © 2025 Apple Inc. and the SwiftUsd project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// This file was generated by SwiftUsd-ast-answerer. Do not edit!
#ifndef __SWIFTUSD_GENERATED_REFERENCE_TYPE_CONFORMANCES_H__
#define __SWIFTUSD_GENERATED_REFERENCE_TYPE_CONFORMANCES_H__

#include "Tf/refBase.h"

#include "Usd/stage.h"

#include "Tf/retainReleaseHelper.h"
#include "FRTProtocols.h"
#include "SwiftCxxMacros.h"

namespace __Overlay {
  bool operatorEqualsEquals(const Pixar::TfRefBase& l,
                            const Pixar::TfRefBase& r);
  bool operatorEqualsEquals(const Pixar::TfSimpleRefBase& l,
                            const Pixar::TfSimpleRefBase& r);
  bool operatorEqualsEquals(const Pixar::UsdStage& l,
                            const Pixar::UsdStage& r);
}

namespace Overlay {}

typedef Pixar::TfRefBase __SwiftUSD_Typedef___ZN3Pixar9TfRefBaseE;
typedef Pixar::TfRefPtr<Pixar::TfRefBase> __SwiftUSD_Typedef___ZN3Pixar9TfRefBaseE_RefPtr;
typedef Pixar::TfRefPtr<const Pixar::TfRefBase> __SwiftUSD_Typedef___ZN3Pixar9TfRefBaseE_ConstRefPtr;
void* _Nonnull _address(Pixar::TfRefBase* _Nonnull)
  SWIFT_NAME(getter:__SwiftUSD_Typedef___ZN3Pixar9TfRefBaseE._address(self:));
inline void __retain__ZN3Pixar9TfRefBaseE(Pixar::TfRefBase* _Nonnull x) {
  Pixar::Tf_RetainReleaseHelper::retain(x);
}
inline void __release__ZN3Pixar9TfRefBaseE(Pixar::TfRefBase* _Nonnull x) {
  Pixar::Tf_RetainReleaseHelper::release(x);
}

Pixar::TfRefBase * _Nullable _fromRawPointer__ZN3Pixar9TfRefBaseE(void* _Nullable)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar9TfRefBaseE._fromRawPointer(_:));


typedef Pixar::TfSimpleRefBase __SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE;
typedef Pixar::TfRefPtr<Pixar::TfSimpleRefBase> __SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE_RefPtr;
typedef Pixar::TfRefPtr<const Pixar::TfSimpleRefBase> __SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE_ConstRefPtr;
void* _Nonnull _address(Pixar::TfSimpleRefBase* _Nonnull)
    SWIFT_NAME(getter:__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE._address(self:));
inline void __retain__ZN3Pixar15TfSimpleRefBaseE(Pixar::TfSimpleRefBase* _Nonnull x) {
    Pixar::Tf_RetainReleaseHelper::retain(x);
}
inline void __release__ZN3Pixar15TfSimpleRefBaseE(Pixar::TfSimpleRefBase* _Nonnull x) {
    Pixar::Tf_RetainReleaseHelper::release(x);
}
Pixar::TfRefPtr<Pixar::TfSimpleRefBase> _asRefPtrType(Pixar::TfSimpleRefBase* _Nonnull)
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE._asRefPtrType(self:));
Pixar::TfSimpleRefBase * _Nullable _fromRefPtrType(const Pixar::TfRefPtr<Pixar::TfSimpleRefBase>&)
    SWIFT_RETURNS_RETAINED
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE._fromRefPtrType(_:));
Pixar::TfSimpleRefBase * _Nullable _fromConstRefPtrType(const Pixar::TfRefPtr<const Pixar::TfSimpleRefBase>&)
    SWIFT_RETURNS_RETAINED
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE._fromConstRefPtrType(_:));
Pixar::TfSimpleRefBase * _Nullable _fromRawPointer__ZN3Pixar15TfSimpleRefBaseE(void* _Nullable)
    SWIFT_RETURNS_RETAINED
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE._fromRawPointer(_:));
Pixar::TfRefPtr<Pixar::TfSimpleRefBase>_nullRefPtr__ZN3Pixar15TfSimpleRefBaseE()
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE_RefPtr._nullPtr());
bool _isNonnull(const Pixar::TfRefPtr<Pixar::TfSimpleRefBase> &)
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE_RefPtr._isNonnull(self:));
bool _isNonnull(const Pixar::TfRefPtr<const Pixar::TfSimpleRefBase> &)
    SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar15TfSimpleRefBaseE_ConstRefPtr._isNonnull(self:));


typedef Pixar::UsdStage __SwiftUSDImportAsMemberTypedef___ZN3Pixar8UsdStageE;

typedef Pixar::UsdStage __SwiftUSD_Typedef___ZN3Pixar8UsdStageE;
typedef Pixar::TfRefPtr<Pixar::UsdStage> __SwiftUSD_Typedef___ZN3Pixar8UsdStageE_RefPtr;
typedef Pixar::TfRefPtr<const Pixar::UsdStage> __SwiftUSD_Typedef___ZN3Pixar8UsdStageE_ConstRefPtr;
typedef Pixar::TfWeakPtr<Pixar::UsdStage> __SwiftUSD_Typedef___ZN3Pixar8UsdStageE_WeakPtr;
typedef Pixar::TfWeakPtr<const Pixar::UsdStage> __SwiftUSD_Typedef___ZN3Pixar8UsdStageE_ConstWeakPtr;
void* _Nonnull _address(Pixar::UsdStage* _Nonnull)
  SWIFT_NAME(getter:__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._address(self:));
inline void __retain__ZN3Pixar8UsdStageE(Pixar::UsdStage* _Nonnull x)
{
  PXR_NS::Tf_RetainReleaseHelper::retain(x);
}
inline void __release__ZN3Pixar8UsdStageE(Pixar::UsdStage* _Nonnull x)
{
  PXR_NS::Tf_RetainReleaseHelper::release(x);
}
Pixar::TfRefPtr<Pixar::UsdStage> _asRefPtrType(Pixar::UsdStage* _Nonnull)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._asRefPtrType(self:));
Pixar::UsdStage * _Nullable _fromRefPtrType(const Pixar::TfRefPtr<Pixar::UsdStage>&)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._fromRefPtrType(_:));
Pixar::UsdStage * _Nullable _fromConstRefPtrType(const Pixar::TfRefPtr<const Pixar::UsdStage>&)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._fromConstRefPtrType(_:));
Pixar::UsdStage * _Nullable _fromRawPointer__ZN3Pixar8UsdStageE(void* _Nullable)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._fromRawPointer(_:));
Pixar::TfRefPtr<Pixar::UsdStage>_nullRefPtr__ZN3Pixar8UsdStageE()
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_RefPtr._nullPtr());
bool _isNonnull(const Pixar::TfRefPtr<Pixar::UsdStage> &)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_RefPtr._isNonnull(self:));
bool _isNonnull(const Pixar::TfRefPtr<const Pixar::UsdStage> &)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_ConstRefPtr._isNonnull(self:));
Pixar::TfWeakPtr<Pixar::UsdStage> _asWeakPtrType(Pixar::UsdStage* _Nonnull)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._asWeakPtrType(self:));
Pixar::UsdStage * _Nullable _fromWeakPtrType(const Pixar::TfWeakPtr<Pixar::UsdStage>&)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._fromWeakPtrType(_:));
Pixar::UsdStage * _Nullable _fromConstWeakPtrType(const Pixar::TfWeakPtr<const Pixar::UsdStage> &)
  SWIFT_RETURNS_RETAINED
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE._fromConstWeakPtrType(_:));
Pixar::TfAnyWeakPtr _asAnyWeakPtr(const Pixar::TfWeakPtr<Pixar::UsdStage>&)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_WeakPtr._asAnyWeakPtr(self:));
Pixar::TfWeakPtr<Pixar::UsdStage>_fromAnyWeakPtr__ZN3Pixar8UsdStageE(const Pixar::TfAnyWeakPtr&)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_WeakPtr._fromAnyWeakPtr(_:));
Pixar::TfWeakPtr<Pixar::UsdStage>_nullWeakPtr__ZN3Pixar8UsdStageE()
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_WeakPtr._nullPtr());
bool _isNonnull(const Pixar::TfWeakPtr<Pixar::UsdStage> &)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_WeakPtr._isNonnull(self:));
bool _isNonnull(const Pixar::TfWeakPtr<const Pixar::UsdStage> &)
  SWIFT_NAME(__SwiftUSD_Typedef___ZN3Pixar8UsdStageE_ConstWeakPtr._isNonnull(self:));

#endif // __SWIFTUSD_GENERATED_REFERENCE_TYPE_CONFORMANCES_H__
