#ifndef __PXR_USDIMAGING_USDSKELIMAGING_H__
#define __PXR_USDIMAGING_USDSKELIMAGING_H__

// UsdSkelImaging
#include <UsdSkelImaging/bindingAPIAdapter.h>
#include <UsdSkelImaging/dataSourceUtils.h>
#include <UsdSkelImaging/dataSourcePrimvar.h>
#include <UsdSkelImaging/utils.h>
#include <UsdSkelImaging/dataSourceResolvedExtComputationPrim.h>
#include <UsdSkelImaging/bindingSchema.h>
#include <UsdSkelImaging/inbetweenShapeSchema.h>
#include <UsdSkelImaging/blendShapeAdapter.h>
#include <UsdSkelImaging/dataSourceSkeletonPrim.h>
#include <UsdSkelImaging/skeletonSchema.h>
#include <UsdSkelImaging/skelGuideData.h>
#include <UsdSkelImaging/dataSourceBindingAPI.h>
#include <UsdSkelImaging/dataSourceResolvedSkeletonPrim.h>
#include <UsdSkelImaging/tokens.h>
#include <UsdSkelImaging/dataSourceAnimationPrim.h>
#include <UsdSkelImaging/extComputations.h>
#include <UsdSkelImaging/resolvedSkeletonSchema.h>
#include <UsdSkelImaging/package.h>
#include <UsdSkelImaging/resolvingSceneIndexPlugin.h>
#include <UsdSkelImaging/skeletonAdapter.h>
#include <UsdSkelImaging/api.h>
#include <UsdSkelImaging/blendShapeSchema.h>
#include <UsdSkelImaging/pointsResolvingSceneIndex.h>
#include <UsdSkelImaging/animationSchema.h>
#include <UsdSkelImaging/skelData.h>
#include <UsdSkelImaging/animationAdapter.h>
#include <UsdSkelImaging/dataSourceBlendShapePrim.h>
#include <UsdSkelImaging/jointInfluencesData.h>
#include <UsdSkelImaging/skeletonResolvingSceneIndex.h>
#include <UsdSkelImaging/blendShapeData.h>
#include <UsdSkelImaging/dataSourceResolvedPointsBasedPrim.h>
#include <UsdSkelImaging/skelRootAdapter.h>
#include <UsdSkelImaging/xformResolver.h>
#endif  // __PXR_USDIMAGING_USDSKELIMAGING_H__
