#ifndef __PXR_BASE_PEGTL_H__
#define __PXR_BASE_PEGTL_H__

// Pegtl
#include <Pegtl/abnf.hpp>
#include <Pegtl/action.hpp>
#include <Pegtl/action_input.hpp>
#include <Pegtl/add_state.hpp>
#include <Pegtl/alphabet.hpp>
#include <Pegtl/analyze.hpp>
#include <Pegtl/analyze_traits.hpp>
#include <Pegtl/any.hpp>
#include <Pegtl/apply.hpp>
#include <Pegtl/apply0.hpp>
#include <Pegtl/apply0_single.hpp>
#include <Pegtl/apply_mode.hpp>
#include <Pegtl/apply_single.hpp>
#include <Pegtl/argv_input.hpp>
#include <Pegtl/ascii.hpp>
#include <Pegtl/at.hpp>
#include <Pegtl/bof.hpp>
#include <Pegtl/bol.hpp>
#include <Pegtl/buffer_input.hpp>
#include <Pegtl/bump.hpp>
#include <Pegtl/bump_help.hpp>
#include <Pegtl/bytes.hpp>
#include <Pegtl/change_action.hpp>
#include <Pegtl/change_action_and_state.hpp>
#include <Pegtl/change_action_and_states.hpp>
#include <Pegtl/change_control.hpp>
#include <Pegtl/change_state.hpp>
#include <Pegtl/change_states.hpp>
#include <Pegtl/check_bytes.hpp>
#include <Pegtl/config.hpp>
#include <Pegtl/control.hpp>
#include <Pegtl/control_action.hpp>
#include <Pegtl/coverage.hpp>
#include <Pegtl/cr_crlf_eol.hpp>
#include <Pegtl/cr_eol.hpp>
#include <Pegtl/crlf_eol.hpp>
#include <Pegtl/cstream_input.hpp>
#include <Pegtl/cstream_reader.hpp>
#include <Pegtl/cstring_reader.hpp>
#include <Pegtl/demangle.hpp>
#include <Pegtl/dependent_false.hpp>
#include <Pegtl/disable.hpp>
#include <Pegtl/disable_action.hpp>
#include <Pegtl/discard.hpp>
#include <Pegtl/discard_input.hpp>
#include <Pegtl/discard_input_on_failure.hpp>
#include <Pegtl/discard_input_on_success.hpp>
#include <Pegtl/enable.hpp>
#include <Pegtl/enable_action.hpp>
#include <Pegtl/enable_control.hpp>
#include <Pegtl/endian.hpp>
#include <Pegtl/endian_gcc.hpp>
#include <Pegtl/endian_win.hpp>
#include <Pegtl/eof.hpp>
#include <Pegtl/eol.hpp>
#include <Pegtl/eol_pair.hpp>
#include <Pegtl/eolf.hpp>
#include <Pegtl/failure.hpp>
#include <Pegtl/file_input.hpp>
#include <Pegtl/file_mapper_posix.hpp>
#include <Pegtl/file_mapper_win32.hpp>
#include <Pegtl/file_reader.hpp>
#include <Pegtl/filesystem.hpp>
#include <Pegtl/forward.hpp>
#include <Pegtl/function.hpp>
#include <Pegtl/has_apply.hpp>
#include <Pegtl/has_apply0.hpp>
#include <Pegtl/has_match.hpp>
#include <Pegtl/has_unwind.hpp>
#include <Pegtl/http.hpp>
#include <Pegtl/identifier.hpp>
#include <Pegtl/if_apply.hpp>
#include <Pegtl/if_must.hpp>
#include <Pegtl/if_must_else.hpp>
#include <Pegtl/if_then.hpp>
#include <Pegtl/if_then_else.hpp>
#include <Pegtl/input_pair.hpp>
#include <Pegtl/instantiate.hpp>
#include <Pegtl/integer.hpp>
#include <Pegtl/internal.hpp>
#include <Pegtl/iri.hpp>
#include <Pegtl/istream_input.hpp>
#include <Pegtl/istream_reader.hpp>
#include <Pegtl/istring.hpp>
#include <Pegtl/iterator.hpp>
#include <Pegtl/json.hpp>
#include <Pegtl/json_pointer.hpp>
#include <Pegtl/lf_crlf_eol.hpp>
#include <Pegtl/lf_eol.hpp>
#include <Pegtl/limit_bytes.hpp>
#include <Pegtl/limit_depth.hpp>
#include <Pegtl/list.hpp>
#include <Pegtl/list_must.hpp>
#include <Pegtl/list_tail.hpp>
#include <Pegtl/list_tail_pad.hpp>
#include <Pegtl/marker.hpp>
#include <Pegtl/match.hpp>
#include <Pegtl/memory_input.hpp>
#include <Pegtl/minus.hpp>
#include <Pegtl/missing_apply.hpp>
#include <Pegtl/missing_apply0.hpp>
#include <Pegtl/mmap_input.hpp>
#include <Pegtl/must.hpp>
#include <Pegtl/must_if.hpp>
#include <Pegtl/normal.hpp>
#include <Pegtl/not_at.hpp>
#include <Pegtl/nothing.hpp>
#include <Pegtl/one.hpp>
#include <Pegtl/opt.hpp>
#include <Pegtl/pad.hpp>
#include <Pegtl/pad_opt.hpp>
#include <Pegtl/parse.hpp>
#include <Pegtl/parse_error.hpp>
#include <Pegtl/parse_tree.hpp>
#include <Pegtl/parse_tree_to_dot.hpp>
#include <Pegtl/path_to_string.hpp>
#include <Pegtl/peek_char.hpp>
#include <Pegtl/peek_mask_uint.hpp>
#include <Pegtl/peek_mask_uint8.hpp>
#include <Pegtl/peek_uint.hpp>
#include <Pegtl/peek_uint8.hpp>
#include <Pegtl/peek_utf16.hpp>
#include <Pegtl/peek_utf32.hpp>
#include <Pegtl/peek_utf8.hpp>
#include <Pegtl/peg.hpp>
#include <Pegtl/pegtl.hpp>
#include <Pegtl/pegtl_string.hpp>
#include <Pegtl/plus.hpp>
#include <Pegtl/position.hpp>
#include <Pegtl/predicates.hpp>
#include <Pegtl/print.hpp>
#include <Pegtl/print_coverage.hpp>
#include <Pegtl/proto3.hpp>
#include <Pegtl/raise.hpp>
#include <Pegtl/range.hpp>
#include <Pegtl/ranges.hpp>
#include <Pegtl/raw_string.hpp>
#include <Pegtl/read_input.hpp>
#include <Pegtl/read_uint.hpp>
#include <Pegtl/rematch.hpp>
#include <Pegtl/remove_first_state.hpp>
#include <Pegtl/remove_last_states.hpp>
#include <Pegtl/rep.hpp>
#include <Pegtl/rep_min.hpp>
#include <Pegtl/rep_min_max.hpp>
#include <Pegtl/rep_one_min_max.hpp>
#include <Pegtl/rep_opt.hpp>
#include <Pegtl/rep_string.hpp>
#include <Pegtl/require.hpp>
#include <Pegtl/require_apply.hpp>
#include <Pegtl/require_apply0.hpp>
#include <Pegtl/result_on_found.hpp>
#include <Pegtl/rewind_mode.hpp>
#include <Pegtl/rules.hpp>
#include <Pegtl/separated_seq.hpp>
#include <Pegtl/seq.hpp>
#include <Pegtl/set_stack_guard.hpp>
#include <Pegtl/shuffle_states.hpp>
#include <Pegtl/sor.hpp>
#include <Pegtl/star.hpp>
#include <Pegtl/star_must.hpp>
#include <Pegtl/state.hpp>
#include <Pegtl/state_control.hpp>
#include <Pegtl/string.hpp>
#include <Pegtl/string_input.hpp>
#include <Pegtl/success.hpp>
#include <Pegtl/to_string.hpp>
#include <Pegtl/trace.hpp>
#include <Pegtl/tracking_mode.hpp>
#include <Pegtl/try_catch_type.hpp>
#include <Pegtl/type_list.hpp>
#include <Pegtl/uint16.hpp>
#include <Pegtl/uint32.hpp>
#include <Pegtl/uint64.hpp>
#include <Pegtl/uint8.hpp>
#include <Pegtl/unescape.hpp>
#include <Pegtl/until.hpp>
#include <Pegtl/unwind_guard.hpp>
#include <Pegtl/uri.hpp>
#include <Pegtl/utf16.hpp>
#include <Pegtl/utf32.hpp>
#include <Pegtl/utf8.hpp>
#include <Pegtl/vector_stack_guard.hpp>
#include <Pegtl/version.hpp>
#include <Pegtl/visit.hpp>
#endif  // __PXR_BASE_PEGTL_H__
