#ifndef __PXR_BASE_PEGTL_H__
#define __PXR_BASE_PEGTL_H__

// Pegtl
#include <Pegtl/rules.hpp>
#include <Pegtl/apply_mode.hpp>
#include <Pegtl/disable_action.hpp>
#include <Pegtl/discard_input_on_success.hpp>
#include <Pegtl/file_input.hpp>
#include <Pegtl/parse_error.hpp>
#include <Pegtl/read_input.hpp>
#include <Pegtl/utf8.hpp>
#include <Pegtl/position.hpp>
#include <Pegtl/require_apply.hpp>
#include <Pegtl/eol_pair.hpp>
#include <Pegtl/tracking_mode.hpp>
#include <Pegtl/string_input.hpp>
#include <Pegtl/change_state.hpp>
#include <Pegtl/change_states.hpp>
#include <Pegtl/change_action.hpp>
#include <Pegtl/config.hpp>
#include <Pegtl/change_action_and_state.hpp>
#include <Pegtl/istream_input.hpp>
#include <Pegtl/must_if.hpp>
#include <Pegtl/argv_input.hpp>
#include <Pegtl/change_action_and_states.hpp>
#include <Pegtl/nothing.hpp>
#include <Pegtl/discard_input_on_failure.hpp>
#include <Pegtl/version.hpp>
#include <Pegtl/change_control.hpp>
#include <Pegtl/eol.hpp>
#include <Pegtl/type_list.hpp>
#include <Pegtl/cstream_input.hpp>
#include <Pegtl/match.hpp>
#include <Pegtl/ascii.hpp>
#include <Pegtl/normal.hpp>
#include <Pegtl/enable_action.hpp>
#include <Pegtl/visit.hpp>
#include <Pegtl/demangle.hpp>
#include <Pegtl/discard_input.hpp>
#include <Pegtl/mmap_input.hpp>
#include <Pegtl/require_apply0.hpp>
#include <Pegtl/memory_input.hpp>
#include <Pegtl/rewind_mode.hpp>
#include <Pegtl/buffer_input.hpp>
#include <Pegtl/parse.hpp>
#include <Pegtl/pegtl.hpp>
#endif  // __PXR_BASE_PEGTL_H__
