#ifndef __PXR_USDIMAGING_USDIMAGING_H__
#define __PXR_USDIMAGING_USDIMAGING_H__

// UsdImaging
#include <UsdImaging/flattenedMaterialBindingsDataSourceProvider.h>
#include <UsdImaging/niPrototypePropagatingSceneIndex.h>
#include <UsdImaging/dataSourceStageGlobals.h>
#include <UsdImaging/capsuleAdapter.h>
#include <UsdImaging/legacyRenderSettingsSceneIndex.h>
#include <UsdImaging/sceneIndex.h>
#include <UsdImaging/delegate.h>
#include <UsdImaging/fieldAdapter.h>
#include <UsdImaging/geometryLightAdapter.h>
#include <UsdImaging/renderProductAdapter.h>
#include <UsdImaging/niInstanceAggregationSceneIndex.h>
#include <UsdImaging/implicitSurfaceMeshUtils.h>
#include <UsdImaging/usdPrimInfoSchema.h>
#include <UsdImaging/version.h>
#include <UsdImaging/lightFilterAdapter.h>
#include <UsdImaging/dataSourcePoints.h>
#include <UsdImaging/dataSourceVolume.h>
#include <UsdImaging/pluginLightAdapter.h>
#include <UsdImaging/flattenedDataSourceProviders.h>
#include <UsdImaging/directMaterialBindingSchema.h>
#include <UsdImaging/dataSourcePrim.h>
#include <UsdImaging/primvarUtils.h>
#include <UsdImaging/portalLightAdapter.h>
#include <UsdImaging/diskLightAdapter.h>
#include <UsdImaging/dataSourcePrimvars.h>
#include <UsdImaging/tetMeshAdapter.h>
#include <UsdImaging/lightAPIAdapter.h>
#include <UsdImaging/types.h>
#include <UsdImaging/dataSourceImplicits-Impl.h>
#include <UsdImaging/geomModelSchema.h>
#include <UsdImaging/prototypeSceneIndexUtils.h>
#include <UsdImaging/dataSourceRelationship.h>
#include <UsdImaging/materialBindingAPIAdapter.h>
#include <UsdImaging/niPrototypePruningSceneIndex.h>
#include <UsdImaging/coordSysAPIAdapter.h>
#include <UsdImaging/motionAPIAdapter.h>
#include <UsdImaging/dataSourceAttributeTypeName.h>
#include <UsdImaging/adapterRegistry.h>
#include <UsdImaging/collectionMaterialBindingSchema.h>
#include <UsdImaging/collectionCache.h>
#include <UsdImaging/sceneIndexCreateArgsSchema.h>
#include <UsdImaging/domeLight_1Adapter.h>
#include <UsdImaging/materialParamUtils.h>
#include <UsdImaging/debugCodes.h>
#include <UsdImaging/sceneIndices.h>
#include <UsdImaging/dataSourceRelocatingSceneIndex.h>
#include <UsdImaging/nurbsPatchAdapter.h>
#include <UsdImaging/pointInstancerAdapter.h>
#include <UsdImaging/renderSettingsFlatteningSceneIndex.h>
#include <UsdImaging/niPrototypeSceneIndex.h>
#include <UsdImaging/meshAdapter.h>
#include <UsdImaging/extentsHintSchema.h>
#include <UsdImaging/coneAdapter.h>
#include <UsdImaging/usdRenderVarSchema.h>
#include <UsdImaging/dataSourceNurbsCurves.h>
#include <UsdImaging/distantLightAdapter.h>
#include <UsdImaging/dataSourcePointInstancer.h>
#include <UsdImaging/primAdapter.h>
#include <UsdImaging/selectionSceneIndex.h>
#include <UsdImaging/dataSourceGprim.h>
#include <UsdImaging/sphereLightAdapter.h>
#include <UsdImaging/tokens.h>
#include <UsdImaging/dataSourceBasisCurves.h>
#include <UsdImaging/dataSourceUsdPrimInfo.h>
#include <UsdImaging/materialBindingsSchema.h>
#include <UsdImaging/flattenedGeomModelDataSourceProvider.h>
#include <UsdImaging/dataSourceMaterial.h>
#include <UsdImaging/basisCurvesAdapter.h>
#include <UsdImaging/sphereAdapter.h>
#include <UsdImaging/collectionAPIAdapter.h>
#include <UsdImaging/lightAdapter.h>
#include <UsdImaging/volumeAdapter.h>
#include <UsdImaging/representedByAncestorPrimAdapter.h>
#include <UsdImaging/api.h>
#include <UsdImaging/usdRenderSettingsSchema.h>
#include <UsdImaging/rerootingContainerDataSource.h>
#include <UsdImaging/domeLightAdapter.h>
#include <UsdImaging/piPrototypePropagatingSceneIndex.h>
#include <UsdImaging/sceneIndexPlugin.h>
#include <UsdImaging/dataSourceTetMesh.h>
#include <UsdImaging/instanceablePrimAdapter.h>
#include <UsdImaging/pointsAdapter.h>
#include <UsdImaging/resolvedAttributeCache.h>
#include <UsdImaging/planeAdapter.h>
#include <UsdImaging/indexProxy.h>
#include <UsdImaging/instanceAdapter.h>
#include <UsdImaging/dataSourceStage.h>
#include <UsdImaging/renderPassAdapter.h>
#include <UsdImaging/dataSourceCamera.h>
#include <UsdImaging/dataSourceMesh.h>
#include <UsdImaging/dataSourceRenderPrims.h>
#include <UsdImaging/drawModeStandin.h>
#include <UsdImaging/rootOverridesSceneIndex.h>
#include <UsdImaging/usdRenderProductSchema.h>
#include <UsdImaging/cubeAdapter.h>
#include <UsdImaging/pluginLightFilterAdapter.h>
#include <UsdImaging/piPrototypeSceneIndex.h>
#include <UsdImaging/gprimAdapter.h>
#include <UsdImaging/drawModeAdapter.h>
#include <UsdImaging/dataSourceAttribute.h>
#include <UsdImaging/unloadedDrawModeSceneIndex.h>
#include <UsdImaging/rerootingSceneIndex.h>
#include <UsdImaging/instancerContext.h>
#include <UsdImaging/dataSourceMapped.h>
#include <UsdImaging/cameraAdapter.h>
#include <UsdImaging/renderSettingsAdapter.h>
#include <UsdImaging/hermiteCurvesAdapter.h>
#include <UsdImaging/apiSchemaAdapter.h>
#include <UsdImaging/rectLightAdapter.h>
#include <UsdImaging/nurbsCurvesAdapter.h>
#include <UsdImaging/adapterManager.h>
#include <UsdImaging/geomModelAPIAdapter.h>
#include <UsdImaging/dataSourceNurbsPatch.h>
#include <UsdImaging/cylinderAdapter.h>
#include <UsdImaging/extentResolvingSceneIndex.h>
#include <UsdImaging/dataSourceAttributeColorSpace.h>
#include <UsdImaging/modelSchema.h>
#include <UsdImaging/stageSceneIndex.h>
#include <UsdImaging/coordSysAdapter.h>
#include <UsdImaging/renderVarAdapter.h>
#include <UsdImaging/geomSubsetAdapter.h>
#include <UsdImaging/geomXformVectorsSchema.h>
#include <UsdImaging/sceneIndexPrimAdapter.h>
#include <UsdImaging/cylinderLightAdapter.h>
#include <UsdImaging/materialAdapter.h>
#include <UsdImaging/textureUtils.h>
#include <UsdImaging/primvarDescCache.h>
#include <UsdImaging/drawModeSceneIndex.h>
#include <UsdImaging/instanceProxyPathTranslationSceneIndex.h>
#include <UsdImaging/materialBindingsResolvingSceneIndex.h>
#include <UsdImaging/materialBindingSchema.h>
#endif  // __PXR_USDIMAGING_USDIMAGING_H__
