#ifndef __PXR_BASE_GF_H__
#define __PXR_BASE_GF_H__

// Gf
#include <Gf/matrix4d.h>
#include <Gf/vec2i.h>
#include <Gf/half.h>
#include <Gf/vec4h.h>
#include <Gf/declare.h>
#include <Gf/bbox3d.h>
#include <Gf/numericCast.h>
#include <Gf/range1f.h>
#include <Gf/ilmbase_halfLimits.h>
#include <Gf/vec4f.h>
#include <Gf/traits.h>
#include <Gf/lineSeg2d.h>
#include <Gf/dualQuatd.h>
#include <Gf/vec3i.h>
#include <Gf/quatd.h>
#include <Gf/limits.h>
#include <Gf/camera.h>
#include <Gf/matrix2f.h>
#include <Gf/homogeneous.h>
#include <Gf/frustum.h>
#include <Gf/range3d.h>
#include <Gf/vec2d.h>
#include <Gf/rotation.h>
#include <Gf/quaternion.h>
#include <Gf/color.h>
#include <Gf/vec3d.h>
#include <Gf/plane.h>
#include <Gf/size2.h>
#include <Gf/timeCode.h>
#include <Gf/line2d.h>
#include <Gf/matrix3f.h>
#include <Gf/range2d.h>
#include <Gf/api.h>
#include <Gf/matrixData.h>
#include <Gf/matrix4f.h>
#include <Gf/rect2i.h>
#include <Gf/vec4d.h>
#include <Gf/range1d.h>
#include <Gf/dualQuath.h>
#include <Gf/transform.h>
#include <Gf/quath.h>
#include <Gf/size3.h>
#include <Gf/quatf.h>
#include <Gf/ray.h>
#include <Gf/gamma.h>
#include <Gf/dualQuatf.h>
#include <Gf/math.h>
#include <Gf/colorSpace.h>
#include <Gf/range3f.h>
#include <Gf/line.h>
#include <Gf/matrix2d.h>
#include <Gf/ilmbase_half.h>
#include <Gf/vec4i.h>
#include <Gf/vec2h.h>
#include <Gf/vec2f.h>
#include <Gf/lineSeg.h>
#include <Gf/vec3f.h>
#include <Gf/ostreamHelpers.h>
#include <Gf/pyBufferUtils.h>
#include <Gf/range2f.h>
#include <Gf/multiInterval.h>
#include <Gf/matrix3d.h>
#include <Gf/interval.h>
#include <Gf/vec3h.h>
#endif  // __PXR_BASE_GF_H__
