#ifndef __PXR_BASE_TF_H__
#define __PXR_BASE_TF_H__

// Tf
#include <PXRBaseTf/anyUniquePtr.h>
#include <PXRBaseTf/anyWeakPtr.h>
#include <PXRBaseTf/api.h>
#include <PXRBaseTf/atomicOfstreamWrapper.h>
#include <PXRBaseTf/atomicRenameUtil.h>
#include <PXRBaseTf/bigRWMutex.h>
#include <PXRBaseTf/bitUtils.h>
#include <PXRBaseTf/callContext.h>
#include <PXRBaseTf/cxxCast.h>
#include <PXRBaseTf/debug.h>
#include <PXRBaseTf/debugCodes.h>
#include <PXRBaseTf/debugNotice.h>
#include <PXRBaseTf/declarePtrs.h>
#include <PXRBaseTf/denseHashMap.h>
#include <PXRBaseTf/denseHashSet.h>
#include <PXRBaseTf/diagnostic.h>
#include <PXRBaseTf/diagnosticBase.h>
#include <PXRBaseTf/diagnosticHelper.h>
#include <PXRBaseTf/diagnosticLite.h>
#include <PXRBaseTf/diagnosticMgr.h>
#include <PXRBaseTf/dl.h>
#include <PXRBaseTf/enum.h>
#include <PXRBaseTf/envSetting.h>
#include <PXRBaseTf/error.h>
#include <PXRBaseTf/errorMark.h>
#include <PXRBaseTf/errorTransport.h>
#include <PXRBaseTf/exception.h>
#include <PXRBaseTf/expiryNotifier.h>
#include <PXRBaseTf/fastCompression.h>
#include <PXRBaseTf/fileUtils.h>
#include <PXRBaseTf/functionRef.h>
#include <PXRBaseTf/functionTraits.h>
#include <PXRBaseTf/getenv.h>
#include <PXRBaseTf/hash.h>
#include <PXRBaseTf/hashmap.h>
#include <PXRBaseTf/hashset.h>
#include <PXRBaseTf/instantiateSingleton.h>
#include <PXRBaseTf/instantiateStacked.h>
#include <PXRBaseTf/instantiateType.h>
#include <PXRBaseTf/iterator.h>
#include <PXRBaseTf/makePyConstructor.h>
#include <PXRBaseTf/mallocTag.h>
#include <PXRBaseTf/meta.h>
#include <PXRBaseTf/notice.h>
#include <PXRBaseTf/noticeRegistry.h>
#include <PXRBaseTf/nullPtr.h>
#include <PXRBaseTf/ostreamMethods.h>
#include <PXRBaseTf/pathUtils.h>
#include <PXRBaseTf/patternMatcher.h>
#include <PXRBaseTf/pch.h>
#include <PXRBaseTf/pointerAndBits.h>
#include <PXRBaseTf/preprocessorUtils.h>
#include <PXRBaseTf/preprocessorUtilsLite.h>
#include <PXRBaseTf/py3Compat.h>
#include <PXRBaseTf/pyAnnotatedBoolResult.h>
#include <PXRBaseTf/pyArg.h>
#include <PXRBaseTf/pyCall.h>
#include <PXRBaseTf/pyCallContext.h>
#include <PXRBaseTf/pyClassMethod.h>
#include <PXRBaseTf/pyContainerConversions.h>
#include <PXRBaseTf/pyEnum.h>
#include <PXRBaseTf/pyError.h>
#include <PXRBaseTf/pyErrorInternal.h>
#include <PXRBaseTf/pyExceptionState.h>
#include <PXRBaseTf/pyFunction.h>
#include <PXRBaseTf/pyIdentity.h>
#include <PXRBaseTf/pyInterpreter.h>
#include <PXRBaseTf/pyInvoke.h>
#include <PXRBaseTf/pyLock.h>
#include <PXRBaseTf/pyModule.h>
#include <PXRBaseTf/pyModuleNotice.h>
#include <PXRBaseTf/pyNoticeWrapper.h>
#include <PXRBaseTf/pyObjectFinder.h>
#include <PXRBaseTf/pyObjWrapper.h>
#include <PXRBaseTf/pyOptional.h>
#include <PXRBaseTf/pyOverride.h>
#include <PXRBaseTf/pyPolymorphic.h>
#include <PXRBaseTf/pyPtrHelpers.h>
#include <PXRBaseTf/pyResultConversions.h>
#include <PXRBaseTf/pySafePython.h>
#include <PXRBaseTf/pySignatureExt.h>
#include <PXRBaseTf/pySingleton.h>
#include <PXRBaseTf/pyStaticTokens.h>
#include <PXRBaseTf/pyTracing.h>
#include <PXRBaseTf/pyUtils.h>
#include <PXRBaseTf/pyWeakObject.h>
#include <PXRBaseTf/pyWrapContext.h>
#include <PXRBaseTf/refBase.h>
#include <PXRBaseTf/refCount.h>
#include <PXRBaseTf/refPtr.h>
#include <PXRBaseTf/refPtrTracker.h>
#include <PXRBaseTf/registryManager.h>
#include <PXRBaseTf/regTest.h>
#include <PXRBaseTf/safeOutputFile.h>
#include <PXRBaseTf/safeTypeCompare.h>
#include <PXRBaseTf/scoped.h>
#include <PXRBaseTf/scopeDescription.h>
#include <PXRBaseTf/scopeDescriptionPrivate.h>
#include <PXRBaseTf/scriptModuleLoader.h>
#include <PXRBaseTf/setenv.h>
#include <PXRBaseTf/singleton.h>
#include <PXRBaseTf/smallVector.h>
#include <PXRBaseTf/span.h>
#include <PXRBaseTf/spinRWMutex.h>
#include <PXRBaseTf/stacked.h>
#include <PXRBaseTf/stackTrace.h>
#include <PXRBaseTf/staticData.h>
#include <PXRBaseTf/staticTokens.h>
#include <PXRBaseTf/status.h>
#include <PXRBaseTf/stl.h>
#include <PXRBaseTf/stopwatch.h>
#include <PXRBaseTf/stringUtils.h>
#include <PXRBaseTf/templateString.h>
#include <PXRBaseTf/tf.h>
#include <PXRBaseTf/token.h>
#include <PXRBaseTf/type_Impl.h>
#include <PXRBaseTf/type.h>
#include <PXRBaseTf/typeFunctions.h>
#include <PXRBaseTf/typeInfoMap.h>
#include <PXRBaseTf/typeNotice.h>
#include <PXRBaseTf/warning.h>
#include <PXRBaseTf/weakBase.h>
#include <PXRBaseTf/weakPtr.h>
#include <PXRBaseTf/weakPtrFacade.h>
#include <PXRBaseTf/wrapTypeHelpers.h>
#include <PXRBaseTf/pxrLZ4/lz4.h>
#include <PXRBaseTf/pxrDoubleConversion/bignum-dtoa.h>
#include <PXRBaseTf/pxrDoubleConversion/bignum.h>
#include <PXRBaseTf/pxrDoubleConversion/cached-powers.h>
#include <PXRBaseTf/pxrDoubleConversion/diy-fp.h>
#include <PXRBaseTf/pxrDoubleConversion/double-conversion.h>
#include <PXRBaseTf/pxrDoubleConversion/fast-dtoa.h>
#include <PXRBaseTf/pxrDoubleConversion/fixed-dtoa.h>
#include <PXRBaseTf/pxrDoubleConversion/ieee.h>
#include <PXRBaseTf/pxrDoubleConversion/strtod.h>
#include <PXRBaseTf/pxrDoubleConversion/utils.h>
#include <PXRBaseTf/pxrPEGTL/pegtl.h>
#include <PXRBaseTf/pxrTslRobinMap/robin_growth_policy.h>
#include <PXRBaseTf/pxrTslRobinMap/robin_hash.h>
#include <PXRBaseTf/pxrTslRobinMap/robin_map.h>
#include <PXRBaseTf/pxrTslRobinMap/robin_set.h>
#include <PXRBaseTf/pxrCLI11/CLI11.h>

#endif // __PXR_BASE_TF_H__
