name: Swift (macOS arm64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        swift: ["6.0.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: 🦦 Install Swift Bundler
        run: |
          curl -o swift-bundler -L https://github.com/wabiverse/wabi-swift-bundler/releases/download/v3.0.4/swift-bundler
          chmod +x ./swift-bundler
          sudo cp ./swift-bundler /usr/local/bin/
          rm ./swift-bundler
      - name: 📦 Build & Bundle
        run: swift bundler bundle -c release --xcodebuild
