name: Run Tests (Microsoft Windows)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.0-release
          tag: 6.0-RELEASE
      - uses: actions/checkout@v4
      - name: 📦 Build
        run: swift build -c debug --target UsdView
