# This source file is taken from github.com/moreSwift/swift-cross-ui
#
# MIT License
#
# Copyright (c) 2022 stackotter.
# Copyright (c) 2026 moreSwift and the swift-cross-ui project authors.
# Modifications Copyright (c) 2026 Wabi Foundation.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# SPDX-License-Identifier: MIT

name: Build UsdView (Android)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on Android
    strategy:
      matrix:
        os: [macos-26]
        swift: ["6.3"]
    runs-on: ${{ matrix.os }}
    env:
      # Release and checksum retrieved from https://www.swift.org/api/v1/install/dev/6.3/android-sdk.json
      SWIFT_RELEASE: swift-6.3-DEVELOPMENT-SNAPSHOT-2026-05-01-a
      SWIFT_ANDROID_SDK_CHECKSUM: 27a0e63264d1b8512522d3a07407ae3d2774eb07d28279ef58e96d1dc2ab720d
      SWIFT_BUNDLER_REVISION: e6909f16ae8b06dc956ba09a3cee1c4863c165bd
      SWIFTUSD_ANDROID_SUPPORT_ENABLED: 1
    steps:
    - name: Setup Xcode 26.5 (Swift 6.3)
      uses: maxim-lobanov/setup-xcode@v1.7.0
      with:
        xcode-version: 'latest-stable'
    - name: Swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Restore Swift Bundler
      id: restore-swift-bundler
      uses: actions/cache/restore@v5
      with:
        path: ./swift-bundler
        key: swift-bundler-${{ env.SWIFT_BUNDLER_REVISION }}
    - name: Build Swift Bundler
      if: steps.restore-swift-bundler.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eux
        checkout="$(pwd)"
        cd ../
        git clone https://github.com/moreSwift/swift-bundler
        cd swift-bundler
        git checkout $SWIFT_BUNDLER_REVISION
        swift build -c debug --product swift-bundler
        cp .build/debug/swift-bundler $checkout/swift-bundler
    - name: Cache Swift Bundler
      id: cache-swift-bundler
      if: steps.restore-swift-bundler.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ./swift-bundler
        key: ${{ steps.restore-swift-bundler.outputs.cache-primary-key }}
    - name: Install Swiftly
      shell: bash
      run: |
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg && \
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory && \
          ~/.swiftly/bin/swiftly init --quiet-shell-followup --skip-install && \
          . "${SWIFTLY_HOME_DIR:-$HOME/.swiftly}/env.sh" && \
          hash -r
    - name: Install Swift 6.3 snapshot
      shell: bash
      run: |
        ~/.swiftly/bin/swiftly install --use $SWIFT_RELEASE
    - name: Install Swift for Android SDK (6.3 snapshot)
      shell: bash
      run: |
        # Adapted from https://www.swift.org/documentation/articles/swift-sdk-for-android-getting-started.html
        ~/.swiftly/bin/swift sdk install \
          https://download.swift.org/swift-6.3-branch/android-sdk/$SWIFT_RELEASE/${SWIFT_RELEASE}_android.artifactbundle.tar.gz \
          --checksum $SWIFT_ANDROID_SDK_CHECKSUM
        # Guess some common places where the swift-sdks file lives
        cd ~/Library/org.swift.swiftpm || cd ~/.config/swiftpm || cd ~/.local/swiftpm || cd ~/.swiftpm || cd /root/.swiftpm
        cd swift-sdks/${SWIFT_RELEASE}_android.artifactbundle/swift-android
        curl -fSL -o ndk.zip https://dl.google.com/android/repository/android-ndk-r27d-$(uname -s).zip
        unzip -qo ndk.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r27d
        ./scripts/setup-android-sdk.sh
    - name: Build UsdView for Android
      shell: bash
      run: |
        set -o pipefail && ./swift-bundler bundle UsdView --platform Android | xcbeautify --preserve-unbeautified --renderer github-actions