name: Swift (macOS arm64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: 🦦 Install Swift Bundler
        run: |
          curl -o swift-bundler -L https://github.com/wabiverse/wabi-swift-bundler/releases/download/v3.0.0/swift-bundler
          chmod +x ./swift-bundler
          cp ./swift-bundler /usr/local/bin
      - name: 📦 Build & Bundle
        run: ./swift-bundler bundle -c release --xcodebuild
